### PR TITLE
Remove couch usage & generate archives instead

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
- Remove pouch
- Generate archive
- Updated dependencies
- Change the way docs are processed so that we don't need lot of memory.
- Sync the generated directory before and after the tool processes docs so that we do incremental generation. This will help for the directory to be synced in the ember-app
- Deployment strategy
- Travis changes

- ~~There are hardcoded links in some docs' description leading to broken links in the api viewer. We should handle their rewrites here.~~
- ~~Some file names refer to other low levels like inflector & rsvp through node_modules folder. Instead of constructing the github url in the ember app, we can generate full file urls by keeping the mapping to their repos here and handling these cases~~

### CODE REVIEW

**Comment by toddjordan** [comment]
I would prefer to break the files up into the directory structure discussed in the issue, something like  _project/version/type/name_, like `ember/2.11.2/class/Ember.Component.json`

**Comment by sivakumar-kailasam** [comment]
Great timing, I was just rewriting the logic to follow this structure to map 1:1 to the app's url

**Comment by fivetanley** [comment]
I am extremely stoked for this!!

**Comment by fivetanley** [comment]
@sivakumar-kailasam @toddjordan How can I help get this over the finish line?

**Comment by sivakumar-kailasam** [comment]
@fivetanley FIxing the hardcoded links in descriptions & updating the file urls with functional full form github urls are tasks atomic enough to be done on either this or the master branch. I've created #24 & #25 with the details

**Comment by toddjordan** [comment]
@fivetanley we are trying to get as much done as we can before emberconf and we have a variety of tasks based on you your level of interest :-) 
Check out the todos in our project: https://github.com/ember-learn/ember-api-docs/projects/1
Feel free to pick up anything.  Just lmk ❤️

**Comment by sivakumar-kailasam** [comment]
Fixes #22 , #18, #17, #7

**Pull request merged**
